import * as React from 'react';
import Head from 'next/head'
import styles from '../styles/Layout.module.css'
import Link from 'next/link';

// heroicons
import { HomeIcon } from '@heroicons/react/outline';
import { FilmIcon } from '@heroicons/react/outline';
import { DesktopComputerIcon } from '@heroicons/react/outline';
import { UsersIcon } from '@heroicons/react/outline';
import { CollectionIcon } from '@heroicons/react/outline';
import { SearchIcon } from '@heroicons/react/outline';
import { DatabaseIcon } from '@heroicons/react/solid';


type LayoutProps = {
    children: React.ReactNode
}
 
const Layout: React.FC<LayoutProps> = ({children}) => {
    return (
        <>
        <Head>
            <title>Another Movie DB</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div id={'layoutGrid'} className={styles.layoutGrid}>
            <header className={styles.header}>
                <div id='logoCont'>
                    <Link href='/'>
                        <a className='px-10 my-10 flex items-center justify-center transition-opacity hover:opacity-80'>
                            <h1 className="text-5xl font-bold">Another Movie DB</h1>
                            <DatabaseIcon className={'inline ml-3 h-14 w-14 text-indigo-900'} />
                        </a>
                    </Link>
                </div>
                <nav className='sm:w-full max-w-screen-md sm:flex flex-wrap'>
                    <NavLink name="Home"/>
                    <NavLink name="Movies"/>
                    <NavLink name="TV"/>
                    <NavLink name="People"/>
                    <NavLink name="Genres"/>
                    <NavLink name="Search"/>
                </nav>
            </header>
            <main className={styles.main}>
                {children}
            </main>
            <footer className={styles.footer}>
                Copyright &#169; 2022 Anthony Medugno.
            </footer>
        </div>
        </>
    );
}
 
export default Layout;

type NavLinkProps = {
    name: string,
}

type className = string; // used to trick tailwindcss extension into providing intellisense for string of classnames

const NavLink: React.FC<NavLinkProps> = ({name}) => {

    const link = (name !== 'Home') ? name.toLowerCase() : '';

    const iconClass : className = "inline h-6 w-6 text-indigo-600 translate-x-10 rotate-0 transition-transform ease-in-out duration-500 group-hover:translate-x-0 group-hover:rotate-[360deg] relative z-[1]";

    const iconMap : {[name: string]: JSX.Element} = {
        'Home' :  <HomeIcon className={iconClass} />,
        'Movies' :  <FilmIcon className={iconClass} />,
        'TV' :  <DesktopComputerIcon className={iconClass} />,
        'People' :  <UsersIcon className={iconClass} />,
        'Genres' :  <CollectionIcon className={iconClass} />,
        'Search' :  <SearchIcon className={iconClass} />
    }

    return(<>
        <Link href={`/${link}`}>
            <a className='group sm:min-w-[7rem] px-1 my-4 mx-auto flex items-center relative'>
                {iconMap[name]} {/* hero icon goes here */}
                <span className='
                ml-2
                invisible group-hover:visible 
                opacity-0 transition-all duration-500 group-hover:opacity-100 
                -translate-x-1/2 group-hover:translate-x-0 relative'>{name}</span>
            </a>
        </Link>
    </>);
}