import * as React from "react"
import { useEffect, useRef } from "react"
import Head from "next/head"
// import styles from '../styles/Layout.module.css'
import Link from "next/link"
import { useRouter } from "next/router"

// heroicons
import { HomeIcon } from "@heroicons/react/outline"
import { FilmIcon } from "@heroicons/react/outline"
import { DesktopComputerIcon } from "@heroicons/react/outline"
// import { UsersIcon } from "@heroicons/react/outline"
// import { CollectionIcon } from "@heroicons/react/outline"
import { SearchIcon } from "@heroicons/react/outline"
import { DatabaseIcon } from "@heroicons/react/solid"
import { MoonIcon } from "@heroicons/react/outline"
import { SunIcon } from "@heroicons/react/outline"

import useMovieTVSearch from "../hooks/useMovieTVSearch"
import ToggleSwitch from "./ToggleSwitch"

type LayoutProps = {
  children: React.ReactNode
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  const [searchTerm, setSearchTerm, handleSearch, searchInputRef] =
    useMovieTVSearch()

  

  return (
    <>
      <Head>
        <title>Another Movie DB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id={"layoutGrid"} className={""}>
        <header
          className={
            "bg-gray-200 dark:bg-slate-900 dark:text-gray-200 flex flex-wrap justify-center xl:justify-between"
          }
        >
          <div id="logoCont">
            <Link href="/">
              <a className="px-10 my-10 flex items-center justify-center transition-opacity hover:opacity-80">
                <h1 className="text-5xl font-bold">Another Movie DB</h1>
                <DatabaseIcon
                  className={
                    "inline ml-3 h-14 w-14 text-indigo-900 dark:text-indigo-400"
                  }
                />
              </a>
            </Link>
          </div>
          <nav className="sm:w-full my-2 max-w-screen-md sm:flex flex-wrap">
            <NavLink name="Home" />
            <NavLink name="TV" />
            <NavLink name="Movies" />
            {/* <NavLink name="People" /> */}
            {/* <NavLink name="Genres" /> */}
            {/* Search Bar */}
            <div className="group sm:min-w-[7rem] px-1 m-auto rounded-full bg-gray-300 dark:bg-slate-700 drop-shadow-sm">
              <form onSubmit={handleSearch} className="flex h-7 items-center">
                <input
                  onChange={(e) => setSearchTerm(e.target.value)}
                  value={searchTerm}
                  ref={searchInputRef}
                  type={"text"}
                  className="h-full w-[85%] pl-2 justify-self-start rounded-full border-none focus:outline-none bg-gray-300 dark:bg-slate-700"
                  placeholder="Find a movie or show..."
                />
                <a href="#" onClick={handleSearch} className="mx-auto">
                  <SearchIcon
                    className={
                      "h-5 w-5 transition-colors text-indigo-600 hover:text-indigo-400  dark:text-indigo-400 dark:hover:text-indigo-300"
                    }
                  />
                </a>
              </form>
            </div>
            {/* Dark Mode Toggle */}
            <ToggleSwitch
              toggleAction={() => {document.getElementsByTagName("html")[0].classList.toggle("dark")}}
              renderStyle={(status, toggleStatus) => (
                <>
                  <div className="grid place-items-center mx-5">
                    <button
                      title="Toggle theme"
                      onClick={toggleStatus}
                      className="p-5 hover:animate-[spin_500ms_ease-in-out] text-indigo-600 dark:text-indigo-400 hover:text-indigo-400 dark:hover:text-indigo-300"
                    >
                      {status ? (
                        <SunIcon className="h-6 w-6" />
                      ) : (
                        <MoonIcon className="h-6 w-6" />
                      )}
                    </button>
                  </div>
                </>
              )}
            />
          </nav>
        </header>
        <main className={"min-h-[100vh]"}>{children}</main>
        <footer
          className={"bg-gray-200 dark:bg-slate-900 p-10 text-center mt-10"}
        >
          <p>Copyright &#169; 2022 Anthony Medugno.</p>
          <p className="my-4">
            All data displayed on this website comes from{" "}
            <a
              className="hover:underline text-indigo-600 dark:text-indigo-300"
              href="https://www.themoviedb.org/?language=en-US"
              target="_blank"
              rel="noreferrer"
            >
              tMDB
            </a>
            .
          </p>
        </footer>
      </div>
    </>
  )
}

export default Layout

type NavLinkProps = {
  name: string
}

type className = string // used to trick tailwindcss extension into providing intellisense for string of classnames

const NavLink: React.FC<NavLinkProps> = ({ name }) => {
  // href default
  let link = `/${name.toLowerCase()}`

  // href for special cases
  if (name === "Home") link = "/"
  if (name === "Search") link = "#"
  if (name === "TV") link = "/shows"

  const iconClass: className =
    "inline h-6 w-6 text-indigo-600 dark:text-indigo-400 sm:translate-x-10 sm:rotate-0 sm:transition-transform sm:ease-in-out sm:duration-500 sm:group-hover:translate-x-0 sm:group-hover:rotate-[360deg] sm:relative z-[1]"

  const iconMap: { [name: string]: JSX.Element } = {
    Home: <HomeIcon className={iconClass} />,
    Movies: <FilmIcon className={iconClass} />,
    TV: <DesktopComputerIcon className={iconClass} />,
    // People: <UsersIcon className={iconClass} />,
    // Genres: <CollectionIcon className={iconClass} />,
    Search: <SearchIcon className={iconClass} />,
  }

  return (
    <>
      <Link href={link}>
        <a className="group w-[7rem] hover:dark:text-indigo-300 sm:dark:hover:text-gray-300 hover:text-indigo-400 sm:hover:text-slate-900 sm:w-auto sm:min-w-[7rem] px-1 my-4 mx-auto flex justify-between sm:justify-start items-center relative">
          {iconMap[name]} {/* hero icon goes here */}
          <span
            className="
                ml-2
                sm:invisible sm:group-hover:visible 
                sm:opacity-0 sm:transition-all sm:duration-500 sm:group-hover:opacity-100 
                sm:-translate-x-1/2 sm:group-hover:translate-x-0 sm:relative"
          >
            {name}
          </span>
        </a>
      </Link>
    </>
  )
}
